//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Caluladora_Prestamo
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarifas
    {
        public int ID_TARIFA { get; set; }
        public double MONTO { get; set; }
        public double MONTO_CUOTA { get; set; }
        public int NO_CUOTA { get; set; }
        public Nullable<int> TIPO { get; set; }
    }
}
